
(async()=>{try{
document.getElementById('pageTitle').textContent='กำลังอ่านข้อมูลจาก Excel…';
const response=await fetch('/api/data',{cache:'no-store'});
if(!response.ok)throw new Error('อ่าน Excel ไม่สำเร็จ (HTTP '+response.status+')');
const DATA=await response.json();
  try {
    const resGeo = await fetch('/thai_provinces.json');
    window.PROVINCES_GEOJSON = resGeo.ok ? await resGeo.json() : null;
  } catch(e) { window.PROVINCES_GEOJSON = null; }
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=v=>typeof v==='number'&&Number.isFinite(v)?v.toLocaleString('th-TH'):'ไม่มีข้อมูล',sum=(a,k)=>a.reduce((n,r)=>n+(typeof r[k]==='number'?r[k]:0),0),uniq=a=>[...new Set(a)],date=v=>new Date(v).toLocaleDateString('th-TH',{day:'numeric',month:'short',year:'numeric',timeZone:'Asia/Bangkok'}),time=v=>v?new Date(v).toLocaleString('th-TH',{day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Bangkok'}):'ไม่ทราบเวลาข้อมูล';
const districts='คลองสาน คลองสามวา คลองเตย คันนายาว จตุจักร จอมทอง ดอนเมือง ดินแดง ดุสิต ตลิ่งชัน ทวีวัฒนา ทุ่งครุ ธนบุรี บางกอกน้อย บางกอกใหญ่ บางกะปิ บางขุนเทียน บางคอแหลม บางซื่อ บางนา บางบอน บางพลัด บางรัก บางเขน บางแค บึงกุ่ม ปทุมวัน ประเวศ ป้อมปราบศัตรูพ่าย พญาไท พระนคร พระโขนง ภาษีเจริญ มีนบุรี ยานนาวา ราชเทวี ราษฎร์บูรณะ ลาดกระบัง ลาดพร้าว วังทองหลาง วัฒนา สวนหลวง สะพานสูง สัมพันธวงศ์ สาทร สายไหม หนองจอก หนองแขม หลักสี่ ห้วยขวาง'.split(' ');
const STALE_MINUTES=1440;
function timestamp(v){if(!v)return NaN;let t=String(v).trim().replace(' ','T');if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}/.test(t))return NaN;if(!/(Z|[+-]\d{2}:?\d{2})$/i.test(t))t+='+07:00';return Date.parse(t)}
function ageMinutes(r){
 if('Report_Date' in r){if(!r.Report_Date || /T00:00(?::00(?:\.0+)?)?(?:Z|[+-]\d{2}:?\d{2})?$/.test(r.Report_Date))return NaN;return (timestamp(r.Ingested_At)-timestamp(r.Report_Date))/60000}
 const source=r.observed_at_th||r.updated_at_source;
 return (timestamp(r.fetched_at_th)-timestamp(source))/60000;
}
const quality=r=>{const age=ageMinutes(r);return !Number.isFinite(age)?'ไม่ทราบเวลาข้อมูล':age<0?'เวลาอนาคต':age<=STALE_MINUTES?'ภายใน 24 ชั่วโมง':'ข้อมูลเก่าเกิน 24 ชั่วโมง'};
const badge=(s,kind='')=>`<span class="badge ${kind}">${esc(s)}</span>`;
const qualityBadge=r=>badge(quality(r),quality(r)==='ภายใน 24 ชั่วโมง'?'good':quality(r)==='เวลาอนาคต'?'bad':'warn');
const statusBadge=s=>badge(s,['ล้นตลิ่ง','วิกฤติ'].includes(s)?'bad':['เตือนภัย','เฝ้าระวัง'].includes(s)?'warn':s==='ปกติ'?'good':'');
const link=(url,text)=>{try{const u=new URL(url);return ['https:','http:'].includes(u.protocol)?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(text)}</a>`:esc(text)}catch{return esc(text)}};
let state={tab:'national',date:uniq(DATA.disasters.map(r=>r.Report_Date.slice(0,10))).sort().at(-1),region:'',province:'',district:''},currentStations=[],currentShelters=[],csvRows=[],map=null,layers=null;
function opts(id,values,first){$(id).innerHTML=(first?`<option value="">${first}</option>`:'')+values.map(v=>`<option value="${esc(v)}">${id==='reportDate'?date(v+'T00:00:00+07:00'):esc(v)}</option>`).join('')}
opts('reportDate',uniq(DATA.disasters.map(r=>r.Report_Date.slice(0,10))).sort());$('reportDate').value=state.date;
opts('region',uniq(DATA.vulnerable.map(r=>r.region)).sort((a,b)=>parseInt(a.match(/\d+/)[0])-parseInt(b.match(/\d+/)[0])),'ทุกเขตสุขภาพ');opts('province',DATA.vulnerable.map(r=>r.province).sort((a,b)=>a.localeCompare(b,'th')),'ทุกจังหวัด');opts('district',districts,'ทุกเขต กทม.');
function card(label,value,unit,note,accent=false){return `<article class="card ${accent?'accent':''}"><div class="eyebrow">${label}</div><div class="number">${fmt(value)}<span class="unit">${unit}</span></div><div class="card-note">${note}</div></article>`}
function metric(label,value){return `<div class="metricline"><span>${label}</span><strong>${value}</strong></div>`}
function bars(rows){let max=Math.max(...rows.map(r=>r.value),1);return rows.map(r=>`<div class="barrow"><button data-province="${esc(r.name)}" title="ดูจังหวัด ${esc(r.name)}">${esc(r.name)}</button><div class="bartrack"><div class="bar" style="width:${r.value/max*100}%"></div></div><strong>${fmt(r.value)}</strong></div>`).join('')||'<p class="empty">ไม่มีรายงานในขอบเขตที่เลือก</p>'}
function table(headers,rows){return `<table><thead><tr>${headers.map((h,i)=>`<th class="${i?'num':''}">${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(row=>`<tr>${row.map((v,i)=>`<td class="${i?'num':''}">${v}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}" class="empty">ไม่มีข้อมูลในขอบเขตที่เลือก</td></tr>`}</tbody></table>`}
function getReports(){return DATA.disasters.filter(r=>r.Report_Date.slice(0,10)===state.date&&r.Current_Status==='กำลังประสบภัย')}
function render(){const bkk=state.tab==='bkk';$('workspace').setAttribute('aria-labelledby',bkk?'tab-bkk':'tab-national');document.querySelectorAll('.tab').forEach(x=>x.setAttribute('aria-selected',String(x.dataset.tab===state.tab)));document.querySelectorAll('.national-filter').forEach(x=>x.classList.toggle('hidden',bkk));$('districtField').classList.toggle('hidden',!bkk);$('shelterPanel').classList.toggle('hidden',!bkk);$('pageTitle').textContent=bkk?'กรุงเทพมหานคร':'สถานการณ์น้ำและพื้นที่ได้รับผลกระทบ';$('pageSub').textContent=bkk?'ติดตามระดับน้ำ ความพร้อมศูนย์พักพิง และข้อมูลรายเขต':'ภาพรวมประเทศไทย รวมกรุงเทพมหานคร · เลือกพื้นที่เพื่อดูรายละเอียด';$('dateLabel').textContent='รายงาน ปภ. '+date(state.date+'T00:00:00+07:00');$('filterNote').textContent=bkk?'รายเขต: ใช้กับสถานีและศูนย์พักพิง':'วันรายงาน: ใช้กับข้อมูล ปภ. เท่านั้น';$('sourceName').textContent=DATA.source;
 const all=getReports(),allowed=DATA.vulnerable.filter(r=>(!state.region||r.region===state.region)&&(!state.province||r.province===state.province)).map(r=>r.province),reports=all.filter(r=>bkk?r.Province==='กรุงเทพมหานคร':allowed.includes(r.Province));
 currentStations=bkk?DATA.bkkStations.filter(r=>r.province==='กรุงเทพมหานคร'&&(!state.district||r.district_or_area===state.district)):DATA.stations.filter(r=>allowed.includes(r.province));currentShelters=bkk?DATA.shelters.filter(r=>!state.district||r.district===state.district):[];
 const fresh=currentStations.filter(r=>quality(r)==='ภายใน 24 ชั่วโมง'),stale=currentStations.filter(r=>quality(r)==='ข้อมูลเก่าเกิน 24 ชั่วโมง'),future=currentStations.filter(r=>quality(r)==='เวลาอนาคต'),severe=fresh.filter(r=>['วิกฤติ','ล้นตลิ่ง'].includes(r.flood_status_source)),affected=uniq(reports.map(r=>r.Province)),households=reports.length?sum(reports,'Affected_Households'):null;
 $('cards').innerHTML=bkk?card('ครัวเรือนตามรายงาน ปภ. ทั้ง กทม.',households,'ครัวเรือน','ไม่แจกแจงรายเขตในไฟล์',true)+card('สถานีคลองในพื้นที่เลือก',currentStations.length,'แห่ง',`ข้อมูลอายุ 0–24 ชั่วโมง ${fmt(fresh.length)} แห่ง`)+card('ผู้พักพิงในพื้นที่เลือก',currentShelters.length?sum(currentShelters,'occupied'):null,'คน',`ศูนย์ในข้อมูล ${fmt(currentShelters.length)} แห่ง`)+card('ที่ว่างตามรายงานต้นทาง',currentShelters.length?sum(currentShelters,'available'):null,'คน','ต้องตรวจความพร้อมกับศูนย์อีกครั้ง'):card('จังหวัดที่มีรายงานภัย',affected.length,'จังหวัด','นับจังหวัดไม่ซ้ำในวันรายงาน',true)+card('ครัวเรือนตามรายงาน',households,'ครัวเรือน','รวมเฉพาะวันและพื้นที่ที่เลือก')+card('จังหวัดแนวโน้มน้ำเพิ่มขึ้น',uniq(reports.filter(r=>r.Water_Level_Trend==='เพิ่มขึ้น').map(r=>r.Province)).length,'จังหวัด','แนวโน้มตามรายงาน ปภ.')+card('สถานีวิกฤติ / ล้นตลิ่ง ข้อมูลสด',severe.length,'แห่ง',`เฉพาะอายุ 0–24 ชั่วโมง จาก ${fmt(currentStations.length)} สถานี`);
 $('alert').textContent=bkk?`สถานีคลองในพื้นที่เลือกมีข้อมูลเก่า ${fmt(stale.length)} จาก ${fmt(currentStations.length)} แห่ง ณ เวลานำเข้า — ตรวจเวลาวัดรายสถานีก่อนใช้งาน`:`ข้อมูล ณ เวลานำเข้า: ${fmt(stale.length)} สถานีเกิน 24 ชั่วโมง และ ${fmt(future.length)} สถานีมีเวลาตรวจวัดอยู่ในอนาคต จึงไม่รวมในยอดสถานีวิกฤติ / ล้นตลิ่งข้อมูลสด`;
 $('mapTitle').textContent=bkk?'สถานีน้ำและศูนย์พักพิง กทม.':'สถานีระดับน้ำทั่วประเทศ';$('mapSubtitle').textContent=bkk?'เฉพาะพิกัดจริงในพื้นที่เลือก · กดจุดเพื่อดูรายละเอียด':'สีจุดพิจารณาสถานะต้นทางและความสดของข้อมูล';$('mapCount').textContent=`${fmt(currentStations.length)} สถานี`;
 if(bkk){$('sideTitle').textContent='ความพร้อมศูนย์พักพิง';$('sideSub').textContent=state.district||'ข้อมูล '+uniq(DATA.shelters.map(r=>r.district)).length+' เขต จาก 50 เขต กทม.';const over=currentShelters.filter(r=>r.occupied>r.capacity),coords=currentShelters.filter(r=>typeof r.latitude==='number'&&typeof r.longitude==='number');$('sideBody').innerHTML=metric('ศูนย์พักพิงในชุดข้อมูล',fmt(currentShelters.length)+' แห่ง')+metric('ความจุตามรายงาน',currentShelters.length?fmt(sum(currentShelters,'capacity'))+' คน':'ไม่มีข้อมูล')+metric('เต็ม / ใกล้เต็ม ตามสถานะต้นทาง',fmt(currentShelters.filter(r=>['เต็ม','ใกล้เต็ม'].includes(r.status_source)).length)+' แห่ง')+metric('ผู้พักเกินความจุที่ระบุ',badge(fmt(over.length)+' แห่ง',over.length?'bad':''))+metric('มีพิกัดพร้อมแสดง',fmt(coords.length)+' / '+fmt(currentShelters.length)+' แห่ง')+'<p class="mini-note">ที่ว่างใช้ยอดต้นทาง ไม่คำนวณจากความจุรวมลบผู้พัก เพราะมีบางศูนย์รับผู้พักเกินความจุ</p>';}
 else{$('sideTitle').textContent='พื้นที่มีครัวเรือนได้รับผลกระทบสูง';$('sideSub').textContent='8 อันดับตามรายงานในขอบเขตที่เลือก · หน่วย: ครัวเรือน';$('sideBody').innerHTML=bars(reports.slice().sort((a,b)=>b.Affected_Households-a.Affected_Households).slice(0,8).map(r=>({name:r.Province,value:r.Affected_Households})));}
 const v=DATA.vulnerable.filter(r=>bkk?r.province==='กรุงเทพมหานคร':affected.includes(r.province));$('vulnerableSub').textContent=bkk?'ฐานประชากรทั้ง กทม. ไม่เปลี่ยนตามตัวกรองเขต เพราะยังไม่มีข้อมูลรายเขต':`ฐานประชากรใน ${fmt(v.length)} จังหวัดที่มีรายงานภัยตามตัวกรอง`;$('vulnerable').innerHTML=[['เด็ก 0–4 ปี','children'],['หญิงตั้งครรภ์','pregnant'],['ผู้สูงอายุ 60 ปีขึ้นไป','elderly']].map(([t,k])=>`<div><span>${t}</span><strong>${v.length?fmt(sum(v,k)):'ไม่มีข้อมูล'} <span class="unit">คน</span></strong></div>`).join('');
 renderAreas(reports,allowed);$('quality').innerHTML=metric('รายงาน ปภ. ผ่านเกณฑ์ 24 ชั่วโมง',fmt(reports.filter(r=>quality(r)==='ภายใน 24 ชั่วโมง').length)+' / '+fmt(reports.length))+metric('รายงาน ปภ. ไม่ทราบเวลาข้อมูล',fmt(reports.filter(r=>quality(r)==='ไม่ทราบเวลาข้อมูล').length))+metric('กลุ่มเปราะบาง','ไม่ทราบเวลาข้อมูล')+(bkk?metric('ศูนย์พักพิงภายใน 24 ชั่วโมง',fmt(currentShelters.filter(r=>quality(r)==='ภายใน 24 ชั่วโมง').length)+' / '+fmt(currentShelters.length)):'')+metric('สถานีอายุ 0–24 ชั่วโมง',fmt(fresh.length)+' แห่ง')+metric('สถานีอายุเกิน 24 ชั่วโมง',fmt(stale.length)+' แห่ง')+metric('เวลาอนาคต / ไม่มีเวลา',fmt(future.length+currentStations.filter(r=>quality(r)==='ไม่ทราบเวลาข้อมูล').length)+' แห่ง')+metric('เวลานำเข้าชุดสถานี',time((bkk?DATA.bkkStations:DATA.stations).map(r=>r.fetched_at_th).filter(Boolean).sort().at(-1)))+'<p class="mini-note">นำเข้าล่าสุดไม่ได้หมายความว่าตรวจวัดล่าสุด ข้อมูลสดในหน้านี้หมายถึงความสดเมื่อดึงเข้าไฟล์เท่านั้น</p>';
 $('actions').innerHTML=bkk?`<p>ตรวจสอบศูนย์ที่มีผู้พักเกินความจุ <b>${fmt(currentShelters.filter(r=>r.occupied>r.capacity).length)} แห่ง</b> ในพื้นที่เลือก</p><p>ติดตามข้อมูลระดับน้ำให้เป็นปัจจุบัน และตรวจตำแหน่งศูนย์พักพิงที่ยังไม่มีพิกัด</p><p class="mini-note">รายงาน ปภ. ให้ยอดครัวเรือนระดับ กทม. จึงยังจัดอันดับเขตจากจำนวนครัวเรือนประสบภัยไม่ได้</p>`:`<p>ติดตามพื้นที่ที่รายงานน้ำเพิ่มขึ้น และสถานีวิกฤติ / ล้นตลิ่งที่เวลาผ่านเกณฑ์</p><p>เพิ่มข้อมูลน้ำอุปโภคบริโภค สุขาภิบาล และผู้ประสบภัยกลุ่มเปราะบางที่ยืนยันแล้ว เพื่อใช้วางแผนงานกรมอนามัย</p><p class="mini-note">ยังไม่มีข้อมูลชุดนี้ใน Excel จึงไม่แสดงคะแนนสุขภาพหรือคะแนนความเสี่ยงที่ตั้งขึ้นเอง</p>`;
 renderStations();if(bkk)renderShelters();renderMap();}
function renderAreas(reports,allowed){if(state.tab==='bkk'){$('areaTitle').textContent='รายละเอียดรายเขต กรุงเทพมหานคร';const rows=districts.filter(x=>!state.district||x===state.district).map(x=>{let s=DATA.shelters.filter(r=>r.district===x),w=DATA.bkkStations.filter(r=>r.province==='กรุงเทพมหานคร'&&r.district_or_area===x);return {name:x,stations:w.length,old:w.filter(r=>quality(r)==='ข้อมูลเก่าเกิน 24 ชั่วโมง').length,centers:s.length,occupied:s.length?sum(s,'occupied'):null,available:s.length?sum(s,'available'):null,over:s.length?s.filter(r=>r.occupied>r.capacity).length:null}}).sort((a,b)=>(b.over||0)-(a.over||0)||(b.occupied||0)-(a.occupied||0));const headers=['เขต','สถานี','ข้อมูลเก่าเกิน 24 ชั่วโมง','ศูนย์ในข้อมูล','ผู้พัก (คน)','ที่ว่าง (คน)','เกินความจุ (แห่ง)'];$('areaTable').innerHTML=table(headers,rows.map(r=>[`<button class="linkbutton" data-district="${esc(r.name)}">${esc(r.name)}</button>`,fmt(r.stations),fmt(r.old),fmt(r.centers),fmt(r.occupied),fmt(r.available),r.over?badge(fmt(r.over),'bad'):fmt(r.over)]));csvRows=[headers,...rows.map(r=>[r.name,r.stations,r.old,r.centers,r.occupied??'ไม่มีข้อมูล',r.available??'ไม่มีข้อมูล',r.over??'ไม่มีข้อมูล'])];}
else{$('areaTitle').textContent='รายละเอียดจังหวัดตามวันรายงาน';const headers=['จังหวัด','เขตสุขภาพ','ครัวเรือน','แนวโน้มน้ำ','สถานะรายงาน','ความสด ณ นำเข้า'];const rows=allowed.map(p=>{const r=reports.find(x=>x.Province===p),v=DATA.vulnerable.find(x=>x.province===p);return {p,r,region:v?.region||'ยังไม่เชื่อมข้อมูล'}}).sort((a,b)=>(b.r?.Affected_Households||0)-(a.r?.Affected_Households||0));$('areaTable').innerHTML=table(headers,rows.map(({p,r,region})=>[`<button class="linkbutton" data-province="${esc(p)}">${esc(p)}</button>`,esc(region),r?fmt(r.Affected_Households):'ไม่มีรายงาน',r?badge(r.Water_Level_Trend,r.Water_Level_Trend==='เพิ่มขึ้น'?'warn':''):'—',r?badge(r.Current_Status,'warn'):badge('ไม่มีรายงานในวันที่เลือก'),r?qualityBadge(r):'—']));csvRows=[headers,...rows.map(({p,r,region})=>[p,region,r?.Affected_Households??'ไม่มีรายงาน',r?.Water_Level_Trend??'',r?.Current_Status??'ไม่มีรายงานในวันที่เลือก',r?quality(r):'ไม่ทราบเวลาข้อมูล'])];}}
function renderStations(){let term=$('search').value.trim(),status=$('statusFilter').value;const rows=currentStations.filter(r=>(!term||(r.station_name+' '+r.district_or_area).includes(term))&&(!status||r.flood_status_source===status)).sort((a,b)=>{let sev={ล้นตลิ่ง:5,วิกฤติ:4,เตือนภัย:3,เฝ้าระวัง:2,ปกติ:1};return (quality(b)==='ภายใน 24 ชั่วโมง')-(quality(a)==='ภายใน 24 ชั่วโมง')||(sev[b.flood_status_source]||0)-(sev[a.flood_status_source]||0)});$('stationSub').textContent=`${fmt(rows.length)} จาก ${fmt(currentStations.length)} สถานี · ระดับน้ำเป็นเมตร รทก. ไม่ใช่ความลึกน้ำท่วม`;$('stationTable').innerHTML=table(['สถานี','พื้นที่','ระดับน้ำ (ม. รทก.)','สถานะต้นทาง','ความสด','เวลาตรวจวัด'],rows.map(r=>[esc(r.station_name),esc(r.district_or_area),typeof r.water_in_m_msl==='number'?r.water_in_m_msl.toFixed(2):'ไม่มีข้อมูล',statusBadge(r.flood_status_source),qualityBadge(r),time(r.observed_at_th)]));}
function renderShelters(){const rows=currentShelters.slice().sort((a,b)=>(b.occupied>b.capacity)-(a.occupied>a.capacity)||b.occupied-a.occupied);$('shelterTable').innerHTML=table(['ศูนย์พักพิง','เขต','ความจุ','ผู้พัก','ที่ว่าง','สถานะ / ตรวจสอบ','ความสด ณ นำเข้า','ปรับปรุงข้อมูล','ตำแหน่ง'],rows.map(r=>[esc(r.shelter_name),esc(r.district),fmt(r.capacity),fmt(r.occupied),fmt(r.available),r.occupied>r.capacity?badge('ผู้พักเกินความจุ','bad'):badge(r.status_source,r.status_source==='เต็ม'?'bad':''),qualityBadge(r),time(r.updated_at_source),r.map_url?link(r.map_url,'เปิดแผนที่'):'ไม่มีลิงก์']));}
function renderMap(){if(!window.L)return;if(!map){$('map').innerHTML='';map=L.map('map',{scrollWheelZoom:false}).setView([13.7,100.5],6);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',maxZoom:18}).addTo(map);layers=L.layerGroup().addTo(map)}layers.clearLayers();
if (window.PROVINCES_GEOJSON && state.tab === 'national') {
    L.geoJSON(window.PROVINCES_GEOJSON, {
        style: function(feature) {
            const prov = feature.properties.pro_th;
            const disaster = DATA.disasters.filter(r => r.Province === prov && r.Report_Date.startsWith(state.date));
            let households = 0;
            if (disaster.length > 0) households = disaster.reduce((s, a) => s + (Number(a.Affected_Households) || 0), 0);
            let color = 'transparent';
            let fillOpacity = 0;
            if (households >= 100000) { color = '#c85850'; fillOpacity = 0.5; } // Red
            else if (households >= 10000) { color = '#d57b4a'; fillOpacity = 0.5; } // Orange
            else if (households >= 1000) { color = '#d5a34a'; fillOpacity = 0.5; } // Yellow
            else if (households > 0) { color = '#087873'; fillOpacity = 0.5; } // Green
            return { color: '#666', weight: 1, fillColor: color, fillOpacity: fillOpacity };
        },
        onEachFeature: function(feature, layer) {
            const prov = feature.properties.pro_th;
            const disaster = DATA.disasters.filter(r => r.Province === prov && r.Report_Date.startsWith(state.date));
            let households = 0;
            if (disaster.length > 0) households = disaster.reduce((s, a) => s + (Number(a.Affected_Households) || 0), 0);
            if (households > 0) {
               layer.bindTooltip(<b></b><br>ผลกระทบ:  ครัวเรือน);
            } else {
               layer.bindTooltip(<b></b>);
            }
        }
    }).addTo(layers);
}
const pts=[];currentStations.forEach(r=>{if(typeof r.latitude!=='number'||typeof r.longitude!=='number')return;let q=quality(r),c=q!=='ภายใน 24 ชั่วโมง'?'#75858b':['วิกฤติ','ล้นตลิ่ง'].includes(r.flood_status_source)?'#c85850':['เตือนภัย','เฝ้าระวัง'].includes(r.flood_status_source)?'#d5a34a':'#087873';L.circleMarker([r.latitude,r.longitude],{radius:5,color:c,weight:1,fillOpacity:.78}).bindPopup(`<b>${esc(r.station_name)}</b><br>${esc(r.district_or_area)}<br>ระดับน้ำ ${esc(r.water_in_m_msl)} ม. รทก.<br>${esc(r.flood_status_source)} · ${esc(q)}<br>${time(r.observed_at_th)}<br>${link(r.source_url,'แหล่งข้อมูล')}`).addTo(layers);pts.push([r.latitude,r.longitude])});currentShelters.forEach(r=>{if(typeof r.latitude!=='number'||typeof r.longitude!=='number')return;L.circleMarker([r.latitude,r.longitude],{radius:8,color:'#087873',fillColor:'#b3eadb',fillOpacity:1,weight:3}).bindPopup(`<b>ศูนย์พักพิง ${esc(r.shelter_name)}</b><br>เขต${esc(r.district)}<br>ผู้พัก ${fmt(r.occupied)} / ความจุ ${fmt(r.capacity)} คน<br>ที่ว่างต้นทาง ${fmt(r.available)} คน`).addTo(layers);pts.push([r.latitude,r.longitude])});map.invalidateSize();if(pts.length)map.fitBounds(pts,{padding:[24,24],maxZoom:13});else map.setView(state.tab==='bkk'?[13.75,100.55]:[15,101],state.tab==='bkk'?10:6);}
document.querySelectorAll('.tab').forEach(x=>x.addEventListener('click',()=>{state.tab=x.dataset.tab;$('search').value='';$('statusFilter').value='';render()}));$('reportDate').addEventListener('change',e=>{state.date=e.target.value;render()});$('region').addEventListener('change',e=>{state.region=e.target.value;state.province='';opts('province',DATA.vulnerable.filter(r=>!state.region||r.region===state.region).map(r=>r.province).sort((a,b)=>a.localeCompare(b,'th')),'ทุกจังหวัด');render()});$('province').addEventListener('change',e=>{state.province=e.target.value;render()});$('district').addEventListener('change',e=>{state.district=e.target.value;render()});$('search').addEventListener('input',renderStations);$('statusFilter').addEventListener('change',renderStations);
document.addEventListener('click',e=>{const p=e.target.closest('[data-province]'),d=e.target.closest('[data-district]');if(p){state.province=p.dataset.province;$('province').value=state.province;render();window.scrollTo({top:0,behavior:'smooth'})}if(d){state.district=d.dataset.district;$('district').value=state.district;render();window.scrollTo({top:0,behavior:'smooth'})}});
$('reset').addEventListener('click',()=>{state.region='';state.province='';state.district='';$('region').value='';$('district').value='';$('search').value='';$('statusFilter').value='';opts('province',DATA.vulnerable.map(r=>r.province).sort((a,b)=>a.localeCompare(b,'th')),'ทุกจังหวัด');render()});
$('methodBtn').addEventListener('click',()=>$('methods').showModal());$('closeMethods').addEventListener('click',()=>$('methods').close());$('methods').addEventListener('click',e=>{if(e.target===$('methods')){let r=$('methods').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('methods').close()}});
$('export').addEventListener('click',()=>{const csv='\uFEFF'+csvRows.map(row=>row.map(v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"').join(',')).join('\r\n');const u=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download=`flood-${state.tab}-${state.date}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)});
const originalRender=render;
render=function(){originalRender();
const bkk=state.tab==='bkk';
const dates=(bkk?DATA.bkkStations:DATA.stations).map(r=>r.fetched_at_th).filter(Boolean).sort();
for(const cell of document.querySelectorAll('#quality .metricline'))if(cell.firstElementChild?.textContent==='เวลานำเข้าชุดสถานี')cell.lastElementChild.textContent=dates.length?time(dates.at(-1)):'ไม่มีเวลา';
document.querySelector('.foot > span:last-child').textContent='อ่าน Excel เมื่อ '+time(DATA.loadedAt)+' • เวลาตรวจวัดขึ้นกับข้อมูลต้นทาง';
if(bkk&&!state.district)document.getElementById('sideSub').textContent='ข้อมูล '+uniq(DATA.shelters.map(r=>r.district)).length+' เขต จาก 50 เขต กทม.';
};
const methodItems=document.querySelectorAll('#methods > ol:first-of-type > li');
methodItems[3].textContent='กทม.: แสดงสถานีที่จังหวัดในข้อมูลต้นทางเป็นกรุงเทพมหานคร ไม่รวมจังหวัดรอบข้าง';
methodItems[4].textContent='ศูนย์พักพิง: จำนวนศูนย์ เขต พิกัด และผู้พักเกินความจุคำนวณจาก Excel ทุกครั้งที่โหลดหน้า';
document.querySelector('#methods p.sub').textContent='อ่าน Excel ผ่านเซิร์ฟเวอร์ทุกครั้งที่เปิดหรือรีเฟรชหน้า บันทึก Excel ก่อนรีเฟรช เวลาข้อมูลต้นทางอาจเก่ากว่าเวลาที่อ่านไฟล์';
render();
// Optional page-scoped agent access uses the same visible navigation.
if(document.modelContext?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'navigate_flood_dashboard',title:'เปิดมุมมองเฝ้าระวังน้ำ',description:'Switch the visible dashboard tab and optionally select a supported DDPM report date.',inputSchema:{type:'object',properties:{tab:{type:'string',enum:['national','bkk']},reportDate:{type:'string',enum:uniq(DATA.disasters.map(r=>r.Report_Date.slice(0,10)))}},required:['tab'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){if(!input||!['national','bkk'].includes(input.tab)||Object.keys(input).some(k=>!['tab','reportDate'].includes(k))||(input.reportDate&&!uniq(DATA.disasters.map(r=>r.Report_Date.slice(0,10))).includes(input.reportDate)))throw new Error('Invalid dashboard selection');state.tab=input.tab;if(input.reportDate){state.date=input.reportDate;$('reportDate').value=state.date}render();return {tab:state.tab,reportDate:state.date,metrics:$('cards').innerText}}},{signal:lifecycle.signal})).catch(()=>{});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}catch{}}
const mapScript=document.createElement('script');mapScript.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';mapScript.onload=renderMap;mapScript.onerror=()=>{$('map').innerHTML='<div class="map-fallback">แผนที่ต้องเชื่อมต่ออินเทอร์เน็ต<br>ยังดูตัวชี้วัดและตารางข้อมูลทั้งหมดได้ด้านล่าง</div>'};document.head.appendChild(mapScript);
}catch(error){document.getElementById('pageTitle').textContent='ไม่สามารถอ่านข้อมูล Excel';document.getElementById('cards').innerHTML='';document.getElementById('alert').textContent=error.message+' — เปิดผ่าน http://127.0.0.1:8765/ แล้วรีเฟรชเพื่อลองใหม่';console.error(error)}})();
