const fs = require('fs');
const vm = require('vm');
const assert = require('node:assert/strict');
const path = require('path');
const context = vm.createContext({console, Utilities: {
  formatDate(date) { return new Date(date.getTime() + 7 * 3600000).toISOString().slice(0,19); }
}});
const code = fs.readFileSync(path.join(__dirname, 'Disater_BKK_DB.gs'), 'utf8');
vm.runInContext(code.replace(/SPREADSHEET_URL: '[^']*'/, "SPREADSHEET_URL: 'https://docs.google.com/spreadsheets/d/test-id/edit'").replace("SOURCE_MODE: 'CSV'", "SOURCE_MODE: 'AUTO'"), context);
context.html = fs.readFileSync(path.join(__dirname, 'source_summary.html'), 'utf8');
const result = vm.runInContext(`(() => {
  const stations = bkkExtractArray_(html, 'waterSummaryList');
  const districts = bkkExtractArray_(html, 'districtList');
  const rows = bkkBuildRows_(stations, districts, new Date('2026-10-01T04:27:53Z'));
  if (!rows.every(r => r.length === BKK_HEADERS.length)) throw Error('Wrong row width');
  return { count: rows.length, rows, stations, districts, headers: BKK_HEADERS };
})()`, context);
assert.equal(result.count, 303);
assert.equal(new Set(result.rows.map(r => r[0])).size, 303);
assert.equal(result.rows.filter(r => r[18] === 'ข้อมูลเก่า').length, 8);
assert.equal(result.rows.filter(r => r[19]).length, 2);
assert.equal(context.bkkLevel_(-99), '');
assert.equal(context.bkkLevel_(null), '');
assert.equal(context.bkkLevel_(0), 0);
assert.equal(context.bkkLevel_(-0.73), -0.73);
assert.equal(context.bkkObservedDate_('2026-10-01T11:26:00').toISOString(), '2026-10-01T04:26:00.000Z');
assert.equal(context.bkkCell_('=IMPORTXML("bad")'), '\'=IMPORTXML("bad")');
assert.throws(() => context.bkkExtractArray_('<html>error</html>', 'waterSummaryList'));
assert.throws(() => context.bkkBuildRows_([], [], new Date()));
assert.throws(() => context.bkkBuildRows_([result.stations[0],result.stations[0]], result.districts, new Date()));
assert.equal(context.bkkExtractArray_('const test = [{"s":"a]b\\\"c", "n":[1,2]}];', 'test').length, 1);
assert.equal(context.bkkParseSpreadsheetUrl_('https://docs.google.com/spreadsheets/d/abc_123-456/edit?gid=999#gid=999'), 'abc_123-456');
assert.equal(context.bkkSpreadsheetId_(), 'test-id');
assert.throws(() => context.bkkParseSpreadsheetUrl_(''));
assert.throws(() => context.bkkParseSpreadsheetUrl_('https://docs.google.com/spreadsheets/d/FILE_ID/edit'));
assert.throws(() => context.bkkParseSpreadsheetUrl_('https://example.com/spreadsheets/d/abc/edit'));
// A failed HTTP request must not open or write the spreadsheet.
let opened = false, released = false;
context.LockService = { getScriptLock: () => ({tryLock: () => true, releaseLock: () => {released = true;}}) };
context.PropertiesService = {getScriptProperties: () => ({getProperty: () => 'test-id',setProperty: () => {}})};
context.UrlFetchApp = {fetch: () => ({getResponseCode: () => 503})};
context.SpreadsheetApp = {openById: () => {opened = true;}};
context.console = {log: () => {}, error: () => {}, warn: () => {}};
assert.throws(() => context.updateBkkWater(), /HTTP 503/);
assert.equal(opened, false);
assert.equal(released, true);
const thaiwaterText = fs.readFileSync(path.join(__dirname, 'thaiwater_canal_sample.json'), 'utf8');
const thaiRows = context.bkkBuildThaiwaterRows_(JSON.parse(thaiwaterText), new Date('2026-10-01T04:27:53Z'));
assert.equal(thaiRows.length, 282);
assert.equal(new Set(thaiRows.map(r => r[0])).size, 282);
assert(thaiRows.every(r => r.length === 23 && r[0].startsWith('THAIWATER:')));
assert(thaiRows.every(r => r[14] === 'ไม่ทราบ' && r[13] === 'ไม่ทราบ'));
assert(thaiRows.every(r => r[21].includes('canal_waterlevel')));
assert(thaiRows.every(r => r[18] === 'ข้อมูลเก่า'));
assert(thaiRows.every(r => JSON.parse(r[22]).station));
assert(thaiRows.every(r => r[9] === '' && r[10] === ''));
context.UrlFetchApp = {fetch: url => url.includes('weather.bangkok') ?
  {getResponseCode: () => 403} : {getResponseCode: () => 200, getContentText: () => thaiwaterText}};
const fallback = context.bkkFetchBatch_();
assert.equal(fallback.rows.length, 282);
assert(fallback.fallbackReason.includes('403'));
context.UrlFetchApp = {fetch: () => ({getResponseCode: () => 200, getContentText: () => context.html})};
assert.equal(context.bkkFetchBatch_().rows.length, 303);
assert.throws(() => context.bkkBuildThaiwaterRows_({result: 'OK', data: []}, new Date()));
const csvHeaders = ['เขต','คลอง','สถานี','วัน-เวลา','สถานะ','ระดับน้ำด้านใน (ม.รทก.)','ระดับน้ำด้านนอก (ม.รทก.)','ระดับน้ำแม่น้ำ (ม.รทก.)','เตือนภัยน้ำท่วมตลิ่ง','ข้อมูล'];
const csvRecord = ['บางเขน','คลองกระเฉด','ค.กระเฉด','01/10/2569 11:25','ขัดข้อง','-0.73','-','0','เตือนภัย',''];
const csvRows = context.bkkBuildCsvRows_([csvHeaders, csvRecord], new Date('2026-10-01T04:27:53Z'), 'testfile');
assert.equal(csvRows[0].length, 23);
assert.equal(csvRows[0][7], '2026-10-01T11:25:00+07:00');
assert.equal(csvRows[0][8], -0.73);
assert.equal(csvRows[0][9], '');
assert.equal(csvRows[0][10], 0);
assert.equal(csvRows[0][13], 'เตือนภัย');
assert.equal(csvRows[0][14], 'ขัดข้อง');
assert.equal(csvRows[0][5], '');
assert.equal(csvRows[0][15], '');
assert.throws(() => context.bkkBuildCsvRows_([['wrong'], ['data']], new Date(), 'id'));
assert.throws(() => context.bkkBuildCsvRows_([csvHeaders, csvRecord, csvRecord], new Date(), 'id'));
console.log('PASS: CSV Thai headers, Buddhist calendar, negative/zero/missing levels, original statuses, missing coordinates, duplicate/header validation.');
const fakeFile = (id, name, time, trashed=false) => ({getId:()=>id,getName:()=>name,getLastUpdated:()=>new Date(time),isTrashed:()=>trashed});
const candidates = [fakeFile('old','WaterSummaryExport.csv',1000),fakeFile('new','WaterSummaryExport (1).CSV',2000),fakeFile('skip','notes.txt',3000),fakeFile('trash','deleted.csv',4000,true)];
context.DriveApp = {getFolderById: id => {assert.equal(id,'1IwS4P84KY95FhxhtctVy1G2PFcDBqy-I'); let i=0;return {getFiles:()=>({hasNext:()=>i<candidates.length,next:()=>candidates[i++]})};}};
assert.equal(context.bkkCsvFile_().getId(),'new');
context.DriveApp = {getFolderById:()=>({getFiles:()=>({hasNext:()=>false})})};
assert.throws(()=>context.bkkCsvFile_(),/ไม่พบไฟล์/);
console.log('PASS: newest CSV selection, folder ID, non-CSV/trashed exclusion, empty folder error.');
console.log('PASS: ThaiWater 282 stations, BMA 403 -> fallback, direct BMA preferred, old timestamps, unknown statuses, source provenance, empty/both-failed protection.');
console.log('PASS: 303 unique stations, 23 columns, timezone, missing/sentinel values, stale flags, malformed/duplicate data, formula escaping, HTTP failure preserves sheet.');
